name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo ${{ secrets.HETZNER_SSH }} > ~/.ssh/ssh
          ssh-add ~/.ssh/ssh
          ssh vpsa@5.161.116.44
          cd VPSA
          ./deploy.sh
