name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: set dbString
        run: |
          echo MONGO=${{ secrets.MONGO }} >> ./backend/dbString.env 
          cat ./backend/dbString.env
      - name: build images
        run: docker-compose build

      - name: fun
        run: |
          docker-compose up
        
        
      - name: tag images
        run: |
          docker tag vpsa_backend sparkyfnay/vpsa_backend:${{ env.RELEASE_VERSION }}
          docker tag vpsa_frontend sparkyfnay/vpsa_frontend:${{ env.RELEASE_VERSION }}
      - name: push container
        run: |
          docker push sparkyfnay/vpsa_backend:${{ env.RELEASE_VERSION }}
          docker push sparkyfnay/vpsa_frontend:${{ env.RELEASE_VERSION }}
