name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      - name: fun
        run: echo ${{ steps.meta.outputs.tags }} 
      - name: set dbString
        run: echo MONGO=${{ secrets.MONGO }} > ./backend/dbString.env 
      - name: build images
        run: docker-compose build
      - name: tag images
        run: |
          docker tag redis:4.0.11 sparkyfnay/vpsa_redis:${{ steps.meta.outputs.tags }} 
          docker tag vpsa_backend sparkyfnay/vpsa_backend:${{ steps.meta.outputs.tags }} 
          docker tag vpsa_frontend sparkyfnay/vpsa_frontend:${{ steps.meta.outputs.tags }} 
      - name: push container
        run: |
          docker push sparkyfnay/vpsa_redis:${{ steps.meta.outputs.tags }} 
          docker push sparkyfnay/vpsa_backend:${{ steps.meta.outputs.tags }} 
          docker push sparkyfnay/vpsa_frontend:${{ steps.meta.outputs.tags }} 
